Update Dns2_booster

diff --git a/Dns2_booster b/Dns2_booster
--- a/Dns2_booster
+++ b/Dns2_booster
@@ -31,7 +31,7 @@ INITIAL_TTL=30
 ######################################
 ######################################
 ######################################
-VER=0.6
+VER=0.7
 case "${DIG_EXEC}" in
  DEFAULT|D)
  _DIG="$(command -v dig)"
@@ -87,30 +87,31 @@ echo "DNSTT Keep-Alive script <Lantin Nohanih>"
 echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
 echo "CTRL + C to close script"
 [[ "${LOOP_DELAY}" -eq 1 ]] && let "LOOP_DELAY++";
-case "${@}" in
- k)
- echo "Performing Keep-Alive only..."
- while true; do
-  check
-  echo '.--. .-.. . .- ... .     .-- .- .. -'
-  sleep ${LOOP_DELAY}
- done
- ;;
- b)
- echo "Performing DNS query boosting only..."
- boost_dns  # Call the boost_dns function
- ;;
- kb)
- echo "Performing Keep-Alive and DNS query boosting simultaneously..."
- while true; do
-  check
-  boost_dns  # Call the boost_dns function
-  echo '.--. .-.. . .- ... .     .-- .- .. -'
-  sleep ${LOOP_DELAY}
- done
- ;;
- *)
- echo "Invalid option. Use 'k' for Keep-Alive, 'b' for DNS query boosting, or 'kb' for both."
- ;;
+case "${1}" in
+  "k")
+    echo "Performing Keep-Alive only..."
+    while true; do
+      check
+      echo '.--. .-.. . .- ... .     .-- .- .. -'
+      sleep ${LOOP_DELAY}
+    done
+    ;;
+  "b")
+    echo "Performing DNS query boosting only..."
+    boost_dns  # Call the boost_dns function
+    ;;
+  "kb")
+    echo "Performing Keep-Alive and DNS query boosting simultaneously..."
+    while true; do
+      check
+      boost_dns  # Call the boost_dns function
+      echo '.--. .-.. . .- ... .     .-- .- .. -'
+      sleep ${LOOP_DELAY}
+    done
+    ;;
+  *)
+    echo "Invalid option. Use 'k' for Keep-Alive, 'b' for DNS query boosting, or 'kb' for both."
+    exit 1
+    ;;
 esac
 exit 0
