Update Equalizer_booster

diff --git a/Equalizer_booster b/Equalizer_booster
--- a/Equalizer_booster
+++ b/Equalizer_booster
@@ -8,15 +8,10 @@ function endscript() {
 
 trap endscript 2 15
 
-# Your DNSTT Nameserver & your Domain `A` Record
-declare -a NS=('sdns.myudp.elcavlaw.com' 'sdns.myudp1.elcavlaw.com' 'sdns.myudph.elcavlaw.com' 'ns-sgfree.elcavlaw.com')
-declare -a A=('myudp.elcavlaw.com' 'myudp1.elcavlaw.com' 'myudph.elcavlaw.com' 'sgfree.elcavlaw.com')
-
-# Add your DNS IP addresses here
 declare -a DNS_IPS=('124.6.181.12' '124.6.181.36')
-declare -a NAME_SERVERS=("${NS[@]}")
+declare -a NAME_SERVERS=('sdns.myudp.elcavlaw.com' 'sdns.myudp1.elcavlaw.com' 'sdns.myudph.elcavlaw.com' 'ns-sgfree.elcavlaw.com')
 
-LOOP_DELAY=1
+LOOP_DELAY=5
 echo -e "\e[1;37mCurrent loop delay is \e[1;33m${LOOP_DELAY}\e[1;37m seconds.\e[0m"
 echo -e "\e[1;37mWould you like to change the loop delay? \e[1;36m[y/n]:\e[0m "
 read -r change_delay
@@ -32,7 +27,7 @@ if [[ "$change_delay" == "y" ]]; then
 fi
 
 DIG_EXEC="DEFAULT"
-CUSTOM_DIG="/data/data/com.termux/files/home/go/bin/fastdig"
+CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
 VER=0.3
 
 case "${DIG_EXEC}" in
@@ -44,14 +39,14 @@ case "${DIG_EXEC}" in
     ;;
 esac
 
-if [ ! "$_DIG" ]; then
-  printf "%b" "Dig command failed to run, please install dnsutils or check the DIG_EXEC & CUSTOM_DIG variable.\n" && exit 1
+if [ ! $(command -v ${_DIG}) ]; then
+  printf "%b" "Dig command failed to run, please install dig(dnsutils) or check the DIG_EXEC & CUSTOM_DIG variable.\n" && exit 1
 fi
 
 # Initialize the counter
 count=1
 
-check() {
+check(){
   local border_color="\e[95m"  # Light magenta color
   local success_color="\e[92m"  # Light green color
   local fail_color="\e[91m"    # Light red color
@@ -75,7 +70,7 @@ check() {
       fi
       echo -e "${border_color}↕${padding}${reset_color}DNS IP: ${T}${padding}${reset_color}"
       echo -e "${border_color}↕${padding}NameServer: ${R}${padding}${reset_color}"
-      echo -e "${border_color}↕${padding}Status: ${STATUS}${padding}${reset_color}"
+      echo -e "${border_color}↕${padding}Status: ${STATUS}${padding}${reset_color}"  # Fixed this line
     done
   done
 
@@ -89,19 +84,18 @@ check() {
 }
 
 countdown() {
-    for i in {5..1}; do
+    for i in 3 2 1 0; do
         echo "Checking started in $i seconds..."
         sleep 1
     done
 }
-
-echo ""
-echo ""
+echo""
+echo""
 echo "Begin...."
-echo ""
-echo ""
+echo""
+echo""
 countdown
-clear
+  clear
 
 # Main loop
 while true; do
